# This source file is part of the Greatdori! open source project
#
# Copyright (c) 2025 the Greatdori! project authors
# Licensed under Apache License v2.0
#
# See https://greatdori.com/LICENSE.txt for license information
# See https://greatdori.com/CONTRIBUTORS.txt for the list of Greatdori! project authors

name: 🪲 Report a bug in app
description: >
  Report a deviation from expected behavior, but not a crash, in app.
labels: [bug, app, triage needed]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        A concise description of what causes the problem.
        Though not required, it may help us to more accurately
        triage the issue as well as understand a non-trivial test case.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction
      description: >
        Provide steps to reproduce the problem.
      value: |
        1. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: >
        Describe the behavior you expected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: >
        Provide the app version, tag, or revision.
        The device running the app and its system version.
      placeholder: Greatdori! 1.0.0, iPhone 16, iOS 26.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: >
        Add screenshots to help explain your problem, if applicable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could help others to work around the problem,
        and us to better understand the problem and its impact.
    validations:
      required: false
